### PR TITLE
Force https in heroku app

### PR DESCRIPTION
**Pull request by Pierstoval**

### CODE REVIEW

**Comment by lyrixx** [comment]
Unfortunately, this does not work :( 
```
>…m/lyrixx/SFLive-Paris2016-Workflow(master) curl  https://symfony-workflow-demo.herokuapp.com/ -I
HTTP/1.1 301 Moved Permanently
Connection: keep-alive
Server: nginx
Date: Sun, 07 Apr 2019 19:45:57 GMT
Content-Type: text/html
Content-Length: 178
Location: https://localhost/
Via: 1.1 vegur

>…m/lyrixx/SFLive-Paris2016-Workflow(master) curl  http://symfony-workflow-demo.herokuapp.com/ -I
HTTP/1.1 301 Moved Permanently
Connection: keep-alive
Server: nginx
Date: Sun, 07 Apr 2019 19:46:01 GMT
Content-Type: text/html
Content-Length: 178
Location: https://localhost/
Via: 1.1 vegur
```

**Comment by Pierstoval** [comment]
Oh yeah, it's not `$server_name`, it's `$host`, my bad, I'll fix this up 🙂  (again, hopefully 🤣 )

**Comment by lyrixx** [comment]
This is better:
```
>…m/lyrixx/SFLive-Paris2016-Workflow(master) curl https://symfony-workflow-demo.herokuapp.com -I
HTTP/1.1 301 Moved Permanently
Connection: keep-alive
Server: nginx
Date: Mon, 08 Apr 2019 07:55:58 GMT
Content-Type: text/html
Content-Length: 178
Location: https://symfony-workflow-demo.herokuapp.com/
Via: 1.1 vegur

>…m/lyrixx/SFLive-Paris2016-Workflow(master) curl http://symfony-workflow-demo.herokuapp.com -I
HTTP/1.1 301 Moved Permanently
Connection: keep-alive
Server: nginx
Date: Mon, 08 Apr 2019 07:56:07 GMT
Content-Type: text/html
Content-Length: 178
Location: https://symfony-workflow-demo.herokuapp.com/
Via: 1.1 vegur
```

**Comment by Pierstoval** [comment]
We probably should check for HTTP headers, since Heroku proxies requests to the backend with HTTP protocol.

Maybe this should be done on the app side instead 😞

**Comment by Pierstoval** [comment]
Trying to search for clues there: https://github.com/heroku/heroku-buildpack-php/tree/master/conf/nginx

**Comment by lyrixx** [comment]
Actually, using `if` in nginx is highly is discouraged, maybe it's that. I will look at it late. Big week in comming

**Comment by Pierstoval** [comment]
I just pushed this change:

```diff
-if ($scheme = http) {
+if ($http_x_forwarded_proto = http) {
```

Feel free to test 😄

**Comment by lyrixx** [comment]
Work like a charm. Thanks a lot !

**Pull request merged**
